# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Sobre Nós
    url: sobrenos
    weight: 10
  - name: Projetos
    url: projetos
    weight: 20
  - name: Notícias
    url: noticias
    weight: 30
  - name: Contacto
    url: contacto
    weight: 40
  #- name: Publications
 #   url: publication
  #  weight: 50
  #- name: Contact
  #  url: contact
   # weight: 60
